# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='time_to_results',
            field=models.DateField(),
        ),
    ]
